// Code generated by file2byteslice. DO NOT EDIT.

package resources

var ConfigJson = []byte("{\n  \"_comment1\": \"下面是屏幕信息\",\n  \"screenWidth\": 640,\n  \"screenHeight\": 480,\n  \"title\": \"外星人入侵\",\n  \"bgColor\": {\n    \"r\": 230,\n    \"g\": 230,\n    \"b\": 230,\n    \"a\": 255\n  },\n  \"_comment2\": \"下面是飞船速度\",\n  \"shipSpeedFactor\": 3,\n  \"_comment3\": \"下面是子弹信息\",\n  \"bulletWidth\": 3,\n  \"bulletHeight\": 15,\n  \"bulletSpeedFactor\": 2,\n  \"bulletColor\": {\n    \"r\": 80,\n    \"g\": 80,\n    \"b\": 80,\n    \"a\": 255\n  },\n  \"_comment4\": \"对子弹和发射时间间隔做点限制\",\n  \"maxBulletNum\": 23,\n  \"bulletInterval\": 150,\n  \"_comment5\": \"下面是外星人移动速度\",\n  \"alienSpeedFactor\": 0.7,\n  \"_conment6\": \"下面是字体信息\",\n  \"titleFontSize\": 24,\n  \"fontSize\": 16,\n  \"smallFontSize\": 12\n}")
